
language = "C"

# Whether to include a comment with the version of cbindgen used to generate the file
# default: false
include_version = true

# Whether to add a `#pragma once` guard
# default: doesn't emit a `#pragma once`
pragma_once = true

[fn]
rename_args = "CamelCase"
args = "auto"


